### ISSUE TITLE
Package gpiodev for Yocto

### ISSUE THREAD

**Issue by jfernandz** [bookwar/python-gpiodev#10]
I was wondering if it would be possible to package this module for Yocto because I will need it and I don't see it in the [openembedded repository](https://git.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python) 

What do you think?

**Comment by jfernandz** [comment]
Well, I did it by myself and it's apparently working for me

https://gist.github.com/jfernandz/325692a871ac406c56fc683de6f4a9f3

Thank you anyway :blush: and awesome library :wink:

**Comment by bookwar** [comment]
@jfernandz Thank you for your interest! I am glad it worked for you.

I don't have much knowledge of Yocto ecosystem, but if you like to publish a package there, feel free to do so.

(while i am going to collect myself together and finally publish it to Pypi and package for Fedora rpm)

**Comment by jfernandz** [comment]
Thank you too @bookwar, I think I could also package it for Debian, but I'd like to do it officially :blush: and I'll need to talk with Debian maintaners about how to do this (I've created custom .deb packages but never any official). I think this may be helpful also for the Raspbian project :smile: 

Yocto works with its particular recipes system, the parser for those recipes is a program called [bitbake](https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html) ... and I think we can suggest openembedded team to include my recipe into their [meta-python](https://layers.openembedded.org/layerindex/branch/master/layer/meta-python/) layer (which contains lots of recipes for python software) :wink:
